Update project dependecies
cuenca-mx/botmaker-python pull request #17
Opened 2022-03-22 18:19 UTC by agarrido19

Update mypy typing stubs, lint and version

2022-03-22 19:46 UTC, andreshndz requested changes
Solo unos cambios

2022-03-22 19:46 UTC, andreshndz commented on botmaker/version.py
> +__version__ = '0.3.5.dev0'  # pragma: no cover
Cambiar la versión

2022-03-22 19:46 UTC, andreshndz commented on botmaker/resources/base.py
> +    _client: ClassVar['botmaker.Client']  # type: ignore # noqa: F821
Checa si no es necesario tener `# noqa: F821`, creo que lo puedes quitar

2022-03-22 19:48 UTC, agarrido19 commented on botmaker/resources/base.py
> +    _client: ClassVar['botmaker.Client']  # type: ignore # noqa: F821
Si se puede pero en python 3.8

2022-03-23 16:27 UTC, andreshndz commented on botmaker/resources/base.py
> +    _client: ClassVar['botmaker.Client']  # type: ignore # noqa: F821
No, mejor deje así

2022-03-23 16:36 UTC, andreshndz approved these changes
Lo veo bien por aquí

2022-03-23 17:31 UTC, alexviquez approved these changes
esta muy legacy este código, pero por ahora vamos a liberar y refactorizamos, crea un issue para eso porfa

2022-03-23 17:49 UTC, merged

2022-03-23 17:52 UTC, agarrido19 commented
@alexviquez https://github.com/cuenca-mx/botmaker-python/issues/18