check a single contact and some cleanups
cuenca-mx/botmaker-python pull request #7
Opened 2019-07-11 18:27 UTC by matin

- It's clearer to keep have `Client.check_whatsapp_contact()` for checking a single contact
- `test_client_404` was missing a cassette
- `botmaker.__version__` should be consistent with the version in `setup.py`

2019-07-11 18:28 UTC, matin commented
/cc @ricardo8990

2019-07-17 18:23 UTC, matin commented
ping @felipaoo

2019-07-18 18:35 UTC, felipao-mx requested changes

2019-07-18 18:35 UTC, felipaoo commented on botmaker/resources/messages.py
> +            checked = cls._client.check_whatsapp_contact(from_, to)
si no hubiera visto la implementación de `check_whatsapp_contact` el nombre `checked` me hace pensar que es un `bool`

2019-07-18 18:35 UTC, felipaoo commented on botmaker/__init__.py
> +__version__ = '0.3.2'
mantener esto `version='0.3.2',`  independiente de `__version__ = '0.3.2'',` vamos a tener el problema. habrá alguna forma de reusar esta variable en el archivo `setup.py`?

2019-07-18 18:36 UTC, merged